### ISSUE TITLE
Question: use with relayphp/Relay.Relay

### ISSUE THREAD

**Issue by cxj** [middlewares/debugbar#10]
I am trying to get this working with [Relay](https://github.com/relayphp/Relay.Relay).  I have not been able to make it work.  Relay is a PSR-15 middleware dispatcher.  I am also using zend-diactoros for my message factory interface.  In theory, these should all work together.

I think my problem is I just don't know exactly what to pass to the Relay queue.  I've tried a few things, including something like the following:
```php
$queue[] = new Middlewares\Debugbar();
```

Can anyone offer any suggestions on how to get it to work?  Thank you.

**Comment by oscarotero** [comment]
Hi. this middleware works with Relay v2 (currently in alpha version). The stable relay version (v1.x) use an old signature for middlewares, not the final signature defined in PSR-15. For v1.x, you can use this middlewares https://github.com/oscarotero/psr7-middlewares

**Comment by cxj** [comment]
Thank you, Oscar.
