### ISSUE TITLE
Inline still tries to load font awesome via url

### ISSUE THREAD

**Issue by mav2287** [middlewares/debugbar#11]
Even when set to inline the debug bar still tried to load the font awesome library. If your vendor folder is above the html root this creates 404 errors. The following are what it tries to load.

https://sample-domain.com/fonts/fontawesome-webfont.woff2?v=4.7.0
https://sample-domain.com/fonts/fontawesome-webfont.woff?v=4.7.0
https://sample-domain.com/fonts/fontawesome-webfont.ttf?v=4.7.0
https://sample-domain.com/fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular

**Comment by oscarotero** [comment]
Yep, this is a known issue. I couldn't find any good way to fix that. Any idea?

**Comment by mav2287** [comment]
I dug into this a bit more and found out that there was an issue that talked about inlining the icons themselves and/or using a CDN for the font, but neither actually happened. In my opinion if they have an inline mode then they need to inline the icons.

All my code lives above the html root folder including my vendor folder so I have to use inline. The issue I have now is that the 404s are causing a conflict with a custom middleware I wrote that logs 404s and locks out IP's that appear to be route sniffing.

All that said the only thing I can think of as a viable solution is to add some logic to this middleware that does something for each needed file that does something like, `IF a route callback isn't defined for the route "/fonts/fontawesome-webfont.woff2?v=4.7.0" THEN go grab the file out of the correct vendor location and return that as the response.`

That would pass through the font files needed and allow the bar to display properly. That same logic could also potentially be applied to the non-inline version as well. It would also allow a defined route to override that if needed. Most importantly though it would take care of the 404's.

**Comment by mav2287** [comment]
This issue can be addressed by using the new ``renderOptions`` feature introduced by Pull Request https://github.com/middlewares/debugbar/pull/12. Using the example in the readme and modifying the following code as needed you can create routes for the assets. This will solve 404 issues without the need to use the broken inline feature.
```
$srcPath = PATH_TO_YOUR_SRC_FOLDER;
$DebugBarResourcesDirPath = $srcPath.'vendor/maximebf/debugbar/src/DebugBar/Resources/';
if( is_dir($DebugBarResourcesDirPath) ) {
    $DebugbarResourcesIterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($DebugBarResourcesDirPath));
    $DebugBarPaths = array_filter(iterator_to_array($DebugbarResourcesIterator), function($file) {
        return $file->isFile();
    });

    foreach (array_keys($DebugBarPaths) as $DebugBarPath ) {
        $filePath = "/".str_replace($srcPath,"",$DebugBarPath);

        $r->addRoute(['GET', 'OPTIONS'], $filePath, function ($request) {
            $path = $srcPath.$request->getUri()->getPath();
            $mime_type = mime_content_type($path) ?: 'application/octet-stream';
            $file_size = filesize($path);

            header("Content-Type: $mime_type");
            header("Content-Length: $file_size");
            $fh = fopen($path, 'rb');
            fpassthru($fh);
            fclose($fh);
        });
    }
}
```
