### ISSUE TITLE
Logging Messages

### ISSUE THREAD

**Issue by mav2287** [middlewares/debugbar#13]
Is there a way to pass messages through the debugbar with this middleware as documented here http://phpdebugbar.com/docs/base-collectors.html#messages ? I'm hoping that is already possible and I am just missing something.

**Comment by oscarotero** [comment]
This middleware just render the debugbar in html responses and handle the ajax http request. It also creates an instance of Debugbar if none has been provided, but you can use your own Debugbar instance:

```php
$debugbar = new StandardDebugBar();
$debugbar['messages']->info('hello world');

$middleware = new Middlewares\Debugbar($debugbar);
```

**Comment by mav2287** [comment]
Thanks! Not sure why I wasn't seeing that.
