### ISSUE TITLE
Allow running from arbitrary server locations (i.e. not server-root).

### ISSUE THREAD

**Issue by Schlaefer** [middlewares/debugbar#7]
Issue: The plugin expects that the vendor folder lives in `http://<server>/vendor`, otherwise asset loading fails to some extend.

`Debugbar->inline()` works to inline CSS and JS, but the fontawesome-font files are still requested from a wrong location.

It would be great if setting a base-URL for assets as in `->getJavascriptRenderer($baseUrl, $basePath)` would be possible.

**Comment by oscarotero** [comment]
You can use a custom Debugbar instance with your own config.

```php
$debugbar = new DebugBar\StandardDebugBar();

$debugbar->getJavascriptRenderer()
    ->setBaseUrl('/assets/debugbar')
    ->setBasePath(__DIR__.'/debugbar');

$middleware[] = new Middlewares\Debugbar($debugbar);
```

**Comment by Schlaefer** [comment]
Oh, I totally missed the setter. Works 1A. Thanks!
