### ISSUE TITLE
Add info that vendor must be accessible via HTTP

### ISSUE THREAD

**Issue by tbreuss** [middlewares/debugbar#8]
You should note somewhere that the vendor directory must be accessible via HTTP. 
If it's not accessible several 404 http errors appear and - of course - the debug bar will not work.
This information is neccessary because often (or should I say normally) the vendor is not accessible via HTTP.

**Comment by oscarotero** [comment]
That's not entirely correct. You can use this middleware without having the vendors in an http accessible place using these two ways:
 - The option [inline](https://github.com/middlewares/debugbar#inlinebool-inline--true) dumps the css/js code in the html
- Or if you're using a front controller pattern, these files not accessible by the server might be handled by your php code so they are read and served by this middleware, [as you can see here](https://github.com/middlewares/debugbar/blob/master/src/Debugbar.php#L80)

Anyway, it's a good idea to explain these techniques in the readme.

**Comment by tbreuss** [comment]
Thank you. This works for me with inline set to true, except including the fonts.

<img width="672" alt="fonts" src="https://user-images.githubusercontent.com/1334161/45277522-991be080-b4c8-11e8-96c2-54a6387889d7.png">

But, as you said an info about these techniques would be helpful.

**Comment by oscarotero** [comment]
Yes, fonts are not inlined, that's why is better to use the front controller technique.

**Comment by tbreuss** [comment]
Solved
