### ISSUE TITLE
Adding to Slim Framework

### ISSUE THREAD

**Issue by fastsol** [middlewares/debugbar#9]
How do I add this into a Slim3 app.  It tried this `$app->add(new Middlewares\Debugbar());` but got this error: **Fatal error: Uncaught RuntimeException: {} is not resolvable in D:\checkinslim\vendor\slim\slim\Slim\CallableResolver.php on line 104**

**Comment by oscarotero** [comment]
Slim v3 uses an old spec of middlewares. 
You can use this package: https://github.com/oscarotero/psr7-middlewares or wait for slim v4 [which support psr-15 middlewares](https://github.com/slimphp/Slim/pull/2379)
